name: 2MS Secret Detection

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  secret-detection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install 2MS
        run: |
          go install github.com/Checkmarx/2ms/v4@latest

      - name: Show 2MS Help
        run: |
          2ms --help
